/*
 * Auto-generated by scripts/regenerate-coverage-preload.ts. Do not hand-edit;
 * run `bun run scripts/regenerate-coverage-preload.ts` to rewrite.
 *
 * `bun test --coverage` only emits rows for files the runner imports. Untested
 * src/infra, src/composition, and src/presenter files are silently absent
 * from the table, which makes the per-file gate trivially pass. This preload
 * side-effect-imports every such file so they appear at 0% (or better) and
 * the gate can fail loudly.
 *
 * Wired ONLY at coverage time, NOT in bunfig.toml. `scripts/check-coverage.ts`
 * spawns `bun test --coverage --preload ./scripts/coverage-preload.ts`.
 *
 * See skills/atelier/references/workflow.md.
 */

// --- src/infra/ ---
import '../src/infra/credential-store-file.ts';
import '../src/infra/logger.ts';
import '../src/infra/threads-graph.ts';
import '../src/infra/tty-terminal.ts';

// --- src/composition/ ---
import '../src/composition/answer.ts';
import '../src/composition/cli-io.ts';
import '../src/composition/env.ts';
import '../src/composition/run-cli.ts';
import '../src/composition/run-post.ts';
import '../src/composition/run-setup.ts';
import '../src/composition/threads-token.ts';

// --- src/presenter/ ---
import '../src/presenter/cli.ts';
import '../src/presenter/hints.ts';
import '../src/presenter/setup-guide.ts';
import '../src/presenter/setup-steps-text.ts';
import '../src/presenter/threads-setup-steps.ts';
