/*
 * Auto-generated by scripts/regenerate-coverage-preload.ts. Do not hand-edit;
 * run `bun run scripts/regenerate-coverage-preload.ts` to rewrite.
 *
 * `bun test --coverage` only emits rows for files the runner imports. Untested
 * src/infra, src/composition, and src/presenter files are silently absent
 * from the table, which makes the per-file gate trivially pass. This preload
 * side-effect-imports every such file so they appear at 0% (or better) and
 * the gate can fail loudly.
 *
 * Wired ONLY at coverage time, NOT in bunfig.toml. `scripts/check-coverage.ts`
 * spawns `bun test --coverage --preload ./scripts/coverage-preload.ts`.
 *
 * See skills/atelier/references/workflow.md.
 */

// --- src/infra/ ---
import '../src/infra/credential-store-file.ts';
import '../src/infra/logger.ts';
import '../src/infra/threads-account.ts';
import '../src/infra/threads-container.ts';
import '../src/infra/threads-graph.ts';
import '../src/infra/threads-http.ts';
import '../src/infra/tty-terminal.ts';
import '../src/infra/x-api.ts';
import '../src/infra/x-http.ts';
import '../src/infra/x-signer.ts';

// --- src/composition/ ---
import '../src/composition/answer.ts';
import '../src/composition/cli-io.ts';
import '../src/composition/env.ts';
import '../src/composition/package-info.ts';
import '../src/composition/run-cli.ts';
import '../src/composition/run-setup.ts';
import '../src/composition/run-threads.ts';
import '../src/composition/threads-token.ts';

// --- src/presenter/ ---
import '../src/presenter/cli-command.ts';
import '../src/presenter/cli.ts';
import '../src/presenter/command-builders.ts';
import '../src/presenter/command-docs.ts';
import '../src/presenter/command-registry.ts';
import '../src/presenter/command-spec.ts';
import '../src/presenter/commands/delete.ts';
import '../src/presenter/commands/docs.ts';
import '../src/presenter/commands/help-json.ts';
import '../src/presenter/commands/post.ts';
import '../src/presenter/commands/setup.ts';
import '../src/presenter/commands/shared-options.ts';
import '../src/presenter/commands/status.ts';
import '../src/presenter/commands/update.ts';
import '../src/presenter/contract.ts';
import '../src/presenter/failure.ts';
import '../src/presenter/hints.ts';
import '../src/presenter/manifest.ts';
import '../src/presenter/post-flags.ts';
import '../src/presenter/read-flags.ts';
import '../src/presenter/setup-guide.ts';
import '../src/presenter/setup-steps-text.ts';
import '../src/presenter/threads-setup-steps.ts';
import '../src/presenter/usage.ts';
import '../src/presenter/x-setup-steps.ts';
